package main

import (
	"os"

	"github.com/ca-gip/artifactory-operator/internal/config"
	"github.com/ca-gip/artifactory-operator/internal/services"
)

func main() {

	// TODO objet config, sortie en exit 1 si configuration invalidation
	// tp := artifactory.BasicAuthTransport{
	// 	Username: os.Getenv("ARTIFACTORY_USERNAME"),
	// 	Password: os.Getenv("ARTIFACTORY_PASSWORD"),
	// }

	// client, err := artifactory.NewClient(os.Getenv("ARTIFACTORY_URL"), tp.Client())
	// if err != nil {
	// 	fmt.Printf("\nerror: %v\n", err)
	// 	return
	// }

	config := &config.ArtifactoryOperatorConfig{
		ArtifactoryServerUrl:      os.Getenv("ARTIFACTORY_URL"),
		ArtifactoryServerUser:     os.Getenv("ARTIFACTORY_USERNAME"),
		ArtifactoryServerPassword: os.Getenv("ARTIFACTORY_PASSWORD"),
	}

	service, _ := services.NewArtifactoryService(config)

	fieldsArtifactory := &services.ArtifactoryInformation{
		Tenant:      "aug", //tenant peut etre nil
		ProjectName: "e4",
		Stages:      []string{"scratch", "staging", "stable"},
		Location:    os.Getenv("LOCATION"),
		Description: "Generated by artifactory operator",
	}

	service.ArtifactoryRepositoryCreate(fieldsArtifactory)
	service.CreateArtifactoryGroup(fieldsArtifactory)
	service.CreateArtifactoryUsers(fieldsArtifactory)
	service.CreateArtifactoryPermissions(fieldsArtifactory)

}
