package main

import (
	"fmt"
	"github.com/atlassian/go-artifactory/pkg/artifactory"
	"github.com/ca-gip/artifactory-operator/internal/services"
	"os"
)

func main() {

	// TODO objet config, sortie en exit 1 si configuration invalidation
	tp := artifactory.BasicAuthTransport{
		Username: os.Getenv("ARTIFACTORY_USERNAME"),
		Password: os.Getenv("ARTIFACTORY_PASSWORD"),
	}

	client, err := artifactory.NewClient(os.Getenv("ARTIFACTORY_URL"), tp.Client())
	if err != nil {
		fmt.Printf("\nerror: %v\n", err)
		return
	}

	fieldsArtifactory := &services.ArtifactoryInformation{
		Tenant:      "aug", //tenant peut etre nil
		ProjectName: "e4",
		Stages:      []string{"scratch", "staging", "stable"},
		Location:    os.Getenv("LOCATION"),
		Description: "Generated by artifactory operator",
	}

	fieldsArtifactory.ArtifactoryRepositoryCreate(client)
	fieldsArtifactory.CreateArtifactoryGroup(client)
	fieldsArtifactory.CreateArtifactoryUsers(client)
	fieldsArtifactory.CreateArtifactoryPermissions(client)

}
