stages:
  - Deploy

Mutu Prod:
  image: agabet/alpine-curl:0.2
  stage: Deploy
  variables:
    HTTP_PROXY: http://$PROXY_RUNNER
    HTTPS_PROXY: http://$PROXY_RUNNER
  script:
    - |
      INVENTORY=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json"  https://awx.os.prodinfo.gca/api/v2/inventories?name=Ansible%20-%20Kube%20-%20Mutu | jq '.results | .[0].id')
      JOB_TEMPLATE=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates?name="Kube-Deployer-Arti" | jq '.results | .[0].id')
      JOB_RUNNING_ID=$(curl -kv -u ${AWX_LOGIN}:${AWX_PASSWORD} -X POST -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates/$JOB_TEMPLATE/launch/ -d "{\"inventory\":$INVENTORY}" | jq .job)
      for i in 1 2 3 4 5
      do 
        RESULT=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD} -H "Content-Type: application/json" "https://awx.os.prodinfo.gca/api/v2/jobs/$JOB_RUNNING_ID" | jq .event_processing_finished)
        if [ "$RESULT" = true ]
        then
         echo "Le job $JOB_RUNNING_ID s'est correctement terminé. Status: $RESULT"
         break
        fi
        sleep 30
      done
      
CAA Hors Prod:
  image: agabet/alpine-curl:0.2
  stage: Deploy
  when: manual
  variables:
    HTTP_PROXY: http://$PROXY_RUNNER
    HTTPS_PROXY: http://$PROXY_RUNNER
  script:
    - |
      INVENTORY=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json"  https://awx.os.prodinfo.gca/api/v2/inventories?name=Ansible%20-%20Kube%20-%20Caa%20%20hors%20prod | jq '.results | .[0].id')
      JOB_TEMPLATE=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates?name="Kube-Deployer-Arti" | jq '.results | .[0].id')
      curl -kv -u ${AWX_LOGIN}:${AWX_PASSWORD} -X POST -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates/$JOB_TEMPLATE/launch/ -d "{\"inventory\":$INVENTORY}"

CACF Hors Prod:
  image: agabet/alpine-curl:0.2
  stage: Deploy
  when: manual
  variables:
    HTTP_PROXY: http://$PROXY_RUNNER
    HTTPS_PROXY: http://$PROXY_RUNNER
  script:
    - |
      INVENTORY=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json"  https://awx.os.prodinfo.gca/api/v2/inventories?name=Ansible%20-%20Kube%20-%20Cacf%20hors%20prod | jq '.results | .[0].id')
      JOB_TEMPLATE=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates?name="Kube-Deployer-Arti" | jq '.results | .[0].id')
      curl -kv -u ${AWX_LOGIN}:${AWX_PASSWORD} -X POST -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates/$JOB_TEMPLATE/launch/ -d "{\"inventory\":$INVENTORY}"

CALF Hors Prod:
  image: agabet/alpine-curl:0.2
  stage: Deploy
  when: manual
  variables:
    HTTP_PROXY: http://$PROXY_RUNNER
    HTTPS_PROXY: http://$PROXY_RUNNER
  script:
    - |
      INVENTORY=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json"  https://awx.os.prodinfo.gca/api/v2/inventories?name=Ansible%20-%20Kube%20-%20Calf%20%20hors%20prod | jq '.results | .[0].id')
      JOB_TEMPLATE=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates?name="Kube-Deployer-Arti" | jq '.results | .[0].id')
      curl -kv -u ${AWX_LOGIN}:${AWX_PASSWORD} -X POST -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates/$JOB_TEMPLATE/launch/ -d "{\"inventory\":$INVENTORY}"

CASA Hors Prod:
  image: agabet/alpine-curl:0.2
  stage: Deploy
  when: manual
  variables:
    HTTP_PROXY: http://$PROXY_RUNNER
    HTTPS_PROXY: http://$PROXY_RUNNER
  script:
    - |
      INVENTORY=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json"  https://awx.os.prodinfo.gca/api/v2/inventories?name=Ansible%20-%20Kube%20-%20Casa%20%20hors%20prod | jq '.results | .[0].id')
      JOB_TEMPLATE=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates?name="Kube-Deployer-Arti" | jq '.results | .[0].id')
      curl -kv -u ${AWX_LOGIN}:${AWX_PASSWORD} -X POST -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates/$JOB_TEMPLATE/launch/ -d "{\"inventory\":$INVENTORY}"

CATF Hors Prod:
  image: agabet/alpine-curl:0.2
  stage: Deploy
  when: manual
  variables:
    HTTP_PROXY: http://$PROXY_RUNNER
    HTTPS_PROXY: http://$PROXY_RUNNER
  script:
    - |
      INVENTORY=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json"  https://awx.os.prodinfo.gca/api/v2/inventories?name=Ansible%20-%20Kube%20-%20Cats%20hors%20prod | jq '.results | .[0].id')
      JOB_TEMPLATE=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates?name="Kube-Deployer-Arti" | jq '.results | .[0].id')
      curl -kv -u ${AWX_LOGIN}:${AWX_PASSWORD} -X POST -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates/$JOB_TEMPLATE/launch/ -d "{\"inventory\":$INVENTORY}"

LCL Hors Prod:
  image: agabet/alpine-curl:0.2
  stage: Deploy
  when: manual
  variables:
    HTTP_PROXY: http://$PROXY_RUNNER
    HTTPS_PROXY: http://$PROXY_RUNNER
  script:
    - |
      INVENTORY=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json"  https://awx.os.prodinfo.gca/api/v2/inventories?name=Ansible%20-%20Kube%20-%20LCL%20%20hors%20prod | jq '.results | .[0].id')
      JOB_TEMPLATE=$(curl -kL -u ${AWX_LOGIN}:${AWX_PASSWORD}  -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates?name="Kube-Deployer-Arti" | jq '.results | .[0].id')
      curl -kv -u ${AWX_LOGIN}:${AWX_PASSWORD} -X POST -H "Content-Type: application/json" https://awx.os.prodinfo.gca/api/v2/job_templates/$JOB_TEMPLATE/launch/ -d "{\"inventory\":$INVENTORY}"