# export ARTI_OP_PASSWORDSTORE_BACKEND_NAMESPACE=
# export ARTI_OP_PASSWORDSTORE_SECRET_NAME_PREFIX=

#ARTIFACTORY
export ARTI_OP_CLUSTER_LOCATION=intranet
export ARTI_OP_ARTIFACTORY_SERVER_URL=https://rct-repository.saas.cagip.gca
export ARTI_OP_ARTIFACTORY_SERVER_USER=admin_operator
export ARTI_OP_ARTIFACTORY_SERVER_PASSWORD=
export ARTI_OP_CLUSTER_DNSSUBDOMAIN=devops
export LDAP_CUSTOMER_OPS_GROUPBASE="CN=DL_KUB_CAGIPHP_OPS,OU=HORS-PROD,OU=CAGIP,OU=PAAS_CONTAINER,OU=Applications,OU=Groupes,O=CA"
export LDAP_VIEWER_GROUPBASE="CN=DL_KUB_CAGIPHP_VIEW,OU=HORS-PROD,OU=CAGIP,OU=PAAS_CONTAINER,OU=Applications,OU=Groupes,O=CA"
export SHARED_REPOSITORY="true"
export ARTI_OP_ARTIFACTORY_SERVER_TOKEN=

#VAULT
export ARTI_OP_VAULT_SERVER_URL=https://vault.saas.cagip.group.gca
export ARTI_OP_VAULT_TOKEN=
