apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory-operator-config
data:
  # Required params

  # The URL for the Artifactory server where registries & users will be created.
  # Put a full URL to the Artifactory instance, including the scheme. Ex: https://an.artifactory.instance/
  ARTI_OP_ARTIFACTORY_SERVER_URL: ""

  # An Aritfactory admin user that can create repositories and users.
  # The ARTI_OP_ARTIFACTORY_SERVER_PASSWORD variable is also required,
  # but you should set it from a Secret (see the rest of the sample deployment).
  ARTI_OP_ARTIFACTORY_SERVER_USER: ""

  # Optional params

  # Location of the cluster : 'intranet' or 'internet'.
  # Default value : 'intranet'.
  # ARTI_OP_CLUSTER_LOCATION: intranet

  # Namespace where passwords for generated Artifactory users will be stored (in K8S Secrets).
  # Default value : 'kube-system'.
  # ARTI_OP_PASSWORDSTORE_BACKEND_NAMESPACE: kube-system

  # Prefix added to the name of Artifactory user Secrets.
  # Default value : 'artifactory-user'.
  # ARTI_OP_PASSWORDSTORE_SECRET_NAME_PREFIX: artifactory-user
