package services

import (
	"testing"
)

func TestArtifactoryRepositoryKey(t *testing.T) {

	fieldsArtifactory := &ArtifactoryInformation{
		Tenant:      "aug", //tenant peut etre nil
		ProjectName: "e4",
		Stages:      []string{"scratch", "staging", "stable"},
		Location:    "intranet",
		Description: "Generated by artifactory operator",
	}

	stage := "scratch"

	keyToTest := artifactoryRepositoryKey(fieldsArtifactory, stage)

	keyShouldBe := "aug-e4-docker-scratch-intranet"

	if keyToTest != keyShouldBe {
		t.Errorf("Artifactory Repository Key was incorrect, got: %v, want: %v.", keyToTest, keyShouldBe)
	}

}
