package services

import (
	"testing"
)

func TestArtifactoryRepositoryKey_SeparateTenant(t *testing.T) {
	fieldsArtifactory := &ArtifactoryInformation{
		Tenant:      "aug",
		ProjectName: "e4",
		Stages:      []string{"scratch", "staging", "stable"},
		Location:    "intranet",
		Description: "Generated by artifactory operator",
	}

	stage := "scratch"

	keyToTest := artifactoryRepositoryKey(fieldsArtifactory, stage)

	keyShouldBe := "aug-e4-docker-scratch-intranet"

	if keyToTest != keyShouldBe {
		t.Errorf("Artifactory Repository Key was incorrect, got: %v, want: %v.", keyToTest, keyShouldBe)
	}

}

func TestArtifactoryRepositoryKey_DuplicateTenant(t *testing.T) {
	fieldsArtifactory := &ArtifactoryInformation{
		Tenant:      "aug",
		ProjectName: "aug-e4",
		Stages:      []string{"scratch", "staging", "stable"},
		Location:    "intranet",
		Description: "Generated by artifactory operator",
	}

	stage := "scratch"

	keyToTest := artifactoryRepositoryKey(fieldsArtifactory, stage)

	keyShouldBe := "aug-e4-docker-scratch-intranet"

	if keyToTest != keyShouldBe {
		t.Errorf("Artifactory Repository Key was incorrect, got: %v, want: %v.", keyToTest, keyShouldBe)
	}

}

func TestPermissionNameRO(t *testing.T) {
	fieldsArtifactory := &ArtifactoryInformation{
		Tenant:      "aug",
		ProjectName: "e4",
		Stages:      []string{"scratch", "staging", "stable"},
		Location:    "intranet",
		Description: "Generated by artifactory operator",
	}

	permission := "ro"

	permissionToTest := permissionName(permission, fieldsArtifactory)

	permissionShouldBe := "aug-e4-docker-allrepos-intranet-ro"

	if permissionToTest != permissionShouldBe {
		t.Errorf("Artifactory permission name was incorrect, got: %v, want: %v.", permissionToTest, permissionShouldBe)
	}

}

func TestPermissionNameRW(t *testing.T) {
	fieldsArtifactory := &ArtifactoryInformation{
		Tenant:      "aug",
		ProjectName: "e4",
		Stages:      []string{"scratch", "staging", "stable"},
		Location:    "intranet",
		Description: "Generated by artifactory operator",
	}

	permission := "rw"

	permissionToTest := permissionName(permission, fieldsArtifactory)

	permissionShouldBe := "aug-e4-docker-allrepos-intranet-rw"

	if permissionToTest != permissionShouldBe {
		t.Errorf("Artifactory permission name was incorrect, got: %v, want: %v.", permissionToTest, permissionShouldBe)
	}

}
