package services

import (
	"context"
	"errors"
	"github.com/atlassian/go-artifactory/pkg/artifactory"
	"github.com/ca-gip/artifactory-operator/internal/types"
	"github.com/ca-gip/artifactory-operator/internal/utils"
	"github.com/rs/zerolog"
	"github.com/stretchr/testify/assert"
	"net/http"
	"testing"
)

type mockArtifactorySecurity struct {
	getGroupWithError          bool
	getGroupWithStatusNotFound bool
}

type mockArtifactoryRepository struct {
	getLocalRepoWithError          bool
	getLocalRepoWithStatusNotFound bool
}

//Prepare mock for Artifactory Security with all combinations
func NewMockArtifactorySecurityWithStatusNotFound() ArtifactorySecurity {
	return &mockArtifactorySecurity{
		getGroupWithError:          false,
		getGroupWithStatusNotFound: true,
	}
}

func NewMockArtifactorySecurityWithError() ArtifactorySecurity {
	return &mockArtifactorySecurity{
		getGroupWithError:          true,
		getGroupWithStatusNotFound: false,
	}
}

func NewMockArtifactorySecurityWithErrorAndNotFound() ArtifactorySecurity {
	return &mockArtifactorySecurity{
		getGroupWithError:          true,
		getGroupWithStatusNotFound: true,
	}
}

func NewMockArtifactorySecurityWithoutError() ArtifactorySecurity {
	return &mockArtifactorySecurity{
		getGroupWithError:          false,
		getGroupWithStatusNotFound: false,
	}
}

//Prepare mock for Artifactory Repository with all combinations
func NewMockArtifactoryRepositoryWithStatusNotFound() ArtifactoryRepository {
	return &mockArtifactoryRepository{
		getLocalRepoWithError:          false,
		getLocalRepoWithStatusNotFound: true,
	}
}

func NewMockArtifactoryRepositoryWithError() ArtifactoryRepository {
	return &mockArtifactoryRepository{
		getLocalRepoWithError:          true,
		getLocalRepoWithStatusNotFound: false,
	}
}

func NewMockArtifactoryRepositoryWithErrorAndNotFound() ArtifactoryRepository {
	return &mockArtifactoryRepository{
		getLocalRepoWithError:          true,
		getLocalRepoWithStatusNotFound: true,
	}
}

func NewMockArtifactoryRepositoryWithoutError() ArtifactoryRepository {
	return &mockArtifactoryRepository{
		getLocalRepoWithError:          false,
		getLocalRepoWithStatusNotFound: false,
	}
}

// Artifactory Security Method mocks
func (m *mockArtifactorySecurity) GetGroup(ctx context.Context, groupName string) (*artifactory.Group, *http.Response, error) {

	if m.getGroupWithStatusNotFound == false && m.getGroupWithError == true {
		return nil, nil, errors.New("dummy error")
	}

	if m.getGroupWithStatusNotFound == true && m.getGroupWithError == false {
		return nil, &http.Response{StatusCode: http.StatusNotFound}, nil
	}

	if m.getGroupWithStatusNotFound == true && m.getGroupWithError == true {
		return nil, &http.Response{StatusCode: http.StatusNotFound}, errors.New("dummy error")
	}

	group := &artifactory.Group{
		Name: artifactory.String("fake group created"),
	}

	resp := &http.Response{
		StatusCode: 200,
	}

	return group, resp, nil
}

func (m *mockArtifactorySecurity) CreateOrReplaceGroup(ctx context.Context, groupName string, group *artifactory.Group) (*http.Response, error) {

	resp := &http.Response{
		StatusCode: http.StatusCreated,
	}

	return resp, nil
}

// Artifactory Repository Method mocks
func (m mockArtifactoryRepository) GetLocal(ctx context.Context, repo string) (*artifactory.LocalRepository, *http.Response, error){
	if m.getLocalRepoWithStatusNotFound == false && m.getLocalRepoWithError == true {
		return nil, nil, errors.New("error when trying to get local repo")
	}

	if m.getLocalRepoWithStatusNotFound == true && m.getLocalRepoWithError == false {
		return nil, &http.Response{StatusCode: http.StatusNotFound}, nil
	}

	if m.getLocalRepoWithStatusNotFound == true && m.getLocalRepoWithError == true {
		return nil, &http.Response{StatusCode: http.StatusNotFound}, errors.New("error 404 not found when trying to get local repo")
	}

	localRepo := &artifactory.LocalRepository{
		Key:                          artifactory.String("docker-repo-mock"),
		RClass:                       artifactory.String("local"),
		PackageType:                  artifactory.String("docker"),
		Description:                  artifactory.String("Generated by artifactory operator"),
		HandleSnapshots:              artifactory.Bool(false),
	}

	resp := &http.Response{
		StatusCode: 200,
	}

	return localRepo, resp, nil
}

func (m mockArtifactoryRepository) CreateLocal(ctx context.Context, repo *artifactory.LocalRepository) (*http.Response, error){
	return &http.Response{StatusCode: http.StatusOK}, nil
}

func (m mockArtifactoryRepository) UpdateLocal(ctx context.Context, repo string, repository *artifactory.LocalRepository) (*http.Response, error){
	return &http.Response{StatusCode: http.StatusOK}, nil
}


func prepareArtifactoryServiceForSecurityTests(fakeError bool, groupNotFound bool) *ArtifactoryService {

	if fakeError == true && groupNotFound == true {
		return &ArtifactoryService{
			logger:              zerolog.Logger{},
			artifactoryClient:   &artifactory.Client{},
			artifactoryUrl:      "https://dummy-arti.example.fr",
			clusterDNSSubdomain: "devops-test",
			Security:            NewMockArtifactorySecurityWithErrorAndNotFound(),
			SkipSharedRepository: "true",
		}
	}

	if fakeError == true && groupNotFound == false {
		return &ArtifactoryService{
			logger:              zerolog.Logger{},
			artifactoryClient:   &artifactory.Client{},
			artifactoryUrl:      "https://dummy-arti.example.fr",
			clusterDNSSubdomain: "devops-test",
			Security:            NewMockArtifactorySecurityWithError(),
			SkipSharedRepository: "true",
		}
	}

	if groupNotFound == true && fakeError == false {
		return &ArtifactoryService{
			logger:              zerolog.Logger{},
			artifactoryClient:   &artifactory.Client{},
			artifactoryUrl:      "https://dummy-arti.example.fr",
			clusterDNSSubdomain: "devops-test",
			Security:            NewMockArtifactorySecurityWithStatusNotFound(),
			SkipSharedRepository: "true",
		}
	}

	return &ArtifactoryService{
		logger:              zerolog.Logger{},
		artifactoryClient:   &artifactory.Client{},
		artifactoryUrl:      "https://dummy-arti.example.fr",
		clusterDNSSubdomain: "devops-test",
		Security:            NewMockArtifactorySecurityWithoutError(),
		SkipSharedRepository: "true",
	}
}

func prepareArtifactoryServiceForRepositoryTests(fakeError bool, repoNotFound bool) *ArtifactoryService {

	if fakeError == true && repoNotFound == true {
		return &ArtifactoryService{
			logger:              zerolog.Logger{},
			artifactoryClient:   &artifactory.Client{},
			artifactoryUrl:      "https://dummy-arti.example.fr",
			clusterDNSSubdomain: "devops-test",
			Repository:          NewMockArtifactoryRepositoryWithErrorAndNotFound(),
			SkipSharedRepository: "true",
		}
	}

	if fakeError == true && repoNotFound == false {
		return &ArtifactoryService{
			logger:              zerolog.Logger{},
			artifactoryClient:   &artifactory.Client{},
			artifactoryUrl:      "https://dummy-arti.example.fr",
			clusterDNSSubdomain: "devops-test",
			Repository:          NewMockArtifactoryRepositoryWithError(),
			SkipSharedRepository: "true",
		}
	}

	if repoNotFound == true && fakeError == false {
		return &ArtifactoryService{
			logger:              zerolog.Logger{},
			artifactoryClient:   &artifactory.Client{},
			artifactoryUrl:      "https://dummy-arti.example.fr",
			clusterDNSSubdomain: "devops-test",
			Repository:          NewMockArtifactoryRepositoryWithStatusNotFound(),
			SkipSharedRepository: "true",
		}
	}

	return &ArtifactoryService{
		logger:              zerolog.Logger{},
		artifactoryClient:   &artifactory.Client{},
		artifactoryUrl:      "https://dummy-arti.example.fr",
		clusterDNSSubdomain: "devops-test",
		Repository:          NewMockArtifactoryRepositoryWithoutError(),
		SkipSharedRepository: "true",
	}
}


func TestCreateArtifactoryRepository(t *testing.T) {

		t.Run("Meta function Artifactory Repository Create should return a list of 4 repository names", func(t *testing.T) {
			//Prepare
			artifactoryService := prepareArtifactoryServiceForRepositoryTests(true, true)
			artifactoryFields := &types.ArtifactoryInformation{
				Tenant:              "caaa",
				ProjectName:         "superbanque",
				Stages:              []string{"scratch","staging","stable"},
				Location:            "intranet",
				Description:         "Created by the test Operator",
				Environment:         "",
				SourceDN:            "",
				ClusterDNSSubdomain: "caaa",
			}

			expectedRepositoryNames := []string{"caaa-superbanque-docker-scratch-intranet",
				"caaa-superbanque-docker-staging-intranet",
				"caaa-superbanque-docker-stable-intranet",
				"docker-stable-intranet-caaa-shared"}

			//Test
			repos, err := artifactoryService.ArtifactoryRepositoryCreate(artifactoryFields)

			//Assert
			assert.Equal(t, nil, err)
			assert.Equal(t, expectedRepositoryNames, repos)
		})

		t.Run("Repo should be created when it does not exist ", func(t *testing.T) {
		//Prepare
		artifactoryService := prepareArtifactoryServiceForRepositoryTests(true, true)
		localRepo := artifactory.LocalRepository{
			Key:                          artifactory.String("docker-repo-mock"),
			RClass:                       artifactory.String("local"),
			PackageType:                  artifactory.String("docker"),
			Description:                  artifactory.String("Generated by artifactory operator"),
			HandleSnapshots:              artifactory.Bool(false),
		}

		//Test
		status, err := artifactoryService.repositoryCreateOrUpdateIfItDoesNotExists("docker-repo-mock",localRepo)
		//Assert

		assert.Equal(t, nil, err)
		assert.Equal(t, "created", status)

	})

	t.Run("Update should not be necessary when repo already exists", func(t *testing.T) {
		//Prepare
		artifactoryService := prepareArtifactoryServiceForRepositoryTests(false, false)
		localRepo := artifactory.LocalRepository{
			Key:                          artifactory.String("docker-repo-mock"),
			RClass:                       artifactory.String("local"),
			PackageType:                  artifactory.String("docker"),
			Description:                  artifactory.String("Generated by artifactory operator"),
			HandleSnapshots:              artifactory.Bool(false),
		}

		//Test
		status, err := artifactoryService.repositoryCreateOrUpdateIfItDoesNotExists("docker-repo-mock",localRepo)
		//Assert

		assert.Equal(t, nil, err)
		assert.Equal(t, "existing", status)
	})

	t.Run("repo should be Updated when there are differences in repo fields", func(t *testing.T) {
		//Prepare
		artifactoryService := prepareArtifactoryServiceForRepositoryTests(false, false)
		localRepo := artifactory.LocalRepository{
			Key:                          artifactory.String("docker-repo-mock"),
			RClass:                       artifactory.String("local"),
			PackageType:                  artifactory.String("maven"),
			Description:                  artifactory.String("Generated by artifactory operator"),
			HandleSnapshots:              artifactory.Bool(false),
		}

		//Test
		status, err := artifactoryService.repositoryCreateOrUpdateIfItDoesNotExists("docker-repo-mock",localRepo)
		//Assert

		assert.Equal(t, nil, err)
		assert.Equal(t, "updated", status)
	})
}

func TestCreateArtifactoryGroup(t *testing.T) {
	t.Run("Error retrieving the security group should be catch and returned", func(t *testing.T) {
		//Prepare
		artifactoryService := prepareArtifactoryServiceForSecurityTests(true, false)
		group := &artifactory.Group{
			Name:            nil,
			Description:     nil,
			AutoJoin:        nil,
			AdminPrivileges: nil,
			Realm:           nil,
			RealmAttributes: nil,
		}

		groupName := "dl_kub_entity_ops"

		expectedError := errors.New("dummy error")

		//Test
		_, err := artifactoryService.createArtifactoryGroup(group, groupName)

		//Assert
		assert.Equal(t, expectedError, err)
	})

	t.Run("Error retrieving the security group and resp status 404 should led to create a new security group", func(t *testing.T) {
		//Prepare
		artifactoryService := prepareArtifactoryServiceForSecurityTests(true, true)
		group := &artifactory.Group{
			Name:            nil,
			Description:     nil,
			AutoJoin:        nil,
			AdminPrivileges: nil,
			Realm:           nil,
			RealmAttributes: nil,
		}

		groupName := "dl_kub_entity_ops"

		expectedResp := &http.Response{StatusCode: http.StatusCreated}

		//Test
		resp, _ := artifactoryService.createArtifactoryGroup(group, groupName)

		//Assert
		assert.Equal(t, expectedResp.StatusCode, resp.StatusCode)
	})

	t.Run("if security group is not found, then it must create it and return a 201 created", func(t *testing.T) {
		//Prepare
		artifactoryService := prepareArtifactoryServiceForSecurityTests(false, true)
		group := &artifactory.Group{
			Name:            nil,
			Description:     nil,
			AutoJoin:        nil,
			AdminPrivileges: nil,
			Realm:           nil,
			RealmAttributes: nil,
		}

		groupName := "dl_kub_entity_ops"

		expectedResp := &http.Response{StatusCode: http.StatusCreated}

		//Test
		resp, _ := artifactoryService.createArtifactoryGroup(group, groupName)

		//Assert
		assert.Equal(t, expectedResp.StatusCode, resp.StatusCode)
	})

	t.Run("ldap group should be formatted correctly", func(t *testing.T){
		//Prepare
		expectedGroup := &artifactory.Group{
			Name:            artifactory.String("dl_container_cagip_hp_cloudops-development_admin"),
			Description:     artifactory.String("created by Artifactory Operator"),
			AutoJoin:        artifactory.Bool(false),
			AdminPrivileges: artifactory.Bool(false),
			Realm:           artifactory.String("ldap"),
			RealmAttributes: artifactory.String("ldapGroupName=DL_CONTAINER_CAGIP_HP_CLOUDOPS-DEVELOPMENT_ADMIN;groupsStrategy=STATIC;groupDn=CN=DL_CONTAINER_CAGIP_HP_CLOUDOPS-DEVELOPMENT_ADMIN,OU=HORS-PROD,OU=CAGIP,OU=PAAS_CONTAINER,OU=Applications,OU=Groupes,O=CA"),
		}

		DN := "CN=DL_CONTAINER_CAGIP_HP_CLOUDOPS-DEVELOPMENT_ADMIN,OU=HORS-PROD,OU=CAGIP,OU=PAAS_CONTAINER,OU=Applications,OU=Groupes,O=CA"

		//test
		cn, _ := utils.ExtractLDAPCN(DN)
		group := computeLDAPGroup(cn,DN)

		//assert
		assert.Equal(t,expectedGroup,group)

	})

}

func TestPermissionNameRO(t *testing.T) {
	fieldsArtifactory := &types.ArtifactoryInformation{
		Tenant:      utils.ArtifactoryTestTenant,
		ProjectName: utils.ArtifactoryTestProjectName,
		Stages:      []string{utils.ArtifactoryStageScratch, utils.ArtifactoryStageStaging, utils.ArtifactoryStageStable},
		Location:    utils.ArtifactoryLocationIntranet,
		Description: utils.ArtifactoryDescription,
	}

	permission := "ro"

	permissionToTest := permissionName(permission, fieldsArtifactory)

	if permissionToTest != utils.ArtifactoryTestPermissionRO {
		t.Errorf("Artifactory permission name was incorrect, got: %v, want: %v.", permissionToTest, utils.ArtifactoryTestPermissionRO)
	}

}

func TestPermissionNameRW(t *testing.T) {
	fieldsArtifactory := &types.ArtifactoryInformation{
		Tenant:      utils.ArtifactoryTestTenant,
		ProjectName: utils.ArtifactoryTestProjectName,
		Stages:      []string{utils.ArtifactoryStageScratch, utils.ArtifactoryStageStaging, utils.ArtifactoryStageStable},
		Location:    utils.ArtifactoryLocationIntranet,
		Description: utils.ArtifactoryDescription,
	}

	permission := "rw"

	permissionToTest := permissionName(permission, fieldsArtifactory)

	if permissionToTest != utils.ArtifactoryTestPermissionRW {
		t.Errorf("Artifactory permission name was incorrect, got: %v, want: %v.", permissionToTest, utils.ArtifactoryTestPermissionRW)
	}

}
