package services

import (
	"reflect"
	"testing"

	"github.com/ca-gip/artifactory-operator/internal/config"
	kubiv1 "github.com/ca-gip/kubi/pkg/apis/ca-gip/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func Test_generateArtifactoryFields_TenantDuplicatedInProjectName(t *testing.T) {
	config := config.ArtifactoryOperatorConfig{
		ClusterLocation: "intranet",
	}

	service, _ := NewProjectService(&config, nil, nil)

	input := &kubiv1.Project{
		ObjectMeta: metav1.ObjectMeta{
			Name: "aug-e4-development",
		},
		Spec: kubiv1.ProjectSpec{
			Tenant:      "aug",
			Environment: "development",
			Project:     "aug-e4",
			Stages: []string{
				"scratch",
			},
		},
	}

	expected := &ArtifactoryInformation{
		Tenant:      "aug",
		ProjectName: "e4",
		Stages: []string{
			"scratch",
		},
		Location:    "intranet",
		Description: "Generated by artifactory operator",
	}

	result, err := service.generateArtifactoryFields(input)

	if err != nil {
		t.Errorf("Unexpected error %v", err)
	}

	if !reflect.DeepEqual(expected, result) {
		t.Errorf("Expected result %v, got %v.", expected, result)
	}

}

func Test_generateArtifactoryFields_CleanProjectName(t *testing.T) {
	config := config.ArtifactoryOperatorConfig{
		ClusterLocation: "intranet",
	}

	service, _ := NewProjectService(&config, nil, nil)

	input := &kubiv1.Project{
		ObjectMeta: metav1.ObjectMeta{
			Name: "aug-e4-development",
		},
		Spec: kubiv1.ProjectSpec{
			Tenant:      "aug",
			Environment: "development",
			Project:     "e4",
			Stages: []string{
				"scratch",
			},
		},
	}

	expected := &ArtifactoryInformation{
		Tenant:      "aug",
		ProjectName: "e4",
		Stages: []string{
			"scratch",
		},
		Location:    "intranet",
		Description: "Generated by artifactory operator",
	}

	result, err := service.generateArtifactoryFields(input)

	if err != nil {
		t.Errorf("Unexpected error %v", err)
	}

	if !reflect.DeepEqual(expected, result) {
		t.Errorf("Expected result %v, got %v.", expected, result)
	}
}
