package services

import (
	"context"
	"fmt"
	"github.com/ca-gip/artifactory-operator/internal/types"
	"github.com/ca-gip/artifactory-operator/internal/utils"
	"github.com/rs/zerolog"
	"gitlab.com/aurelien.gabet/go-xray-cli/pkg/xray"
	"net/http"
	"os"
	"regexp"
)

type XrayService struct {
	logger       zerolog.Logger
	xrayClient   *xray.Client
	xrayBinMgrID string
	Credentials  *xray.GetToken
}

func NewXrayService(operatorConfig *types.ArtifactoryOperatorConfig) (*XrayService, error) {

	logger := utils.Log.With().Str("service", "xray").Logger()

	credentials := xray.GetToken{
		Name: operatorConfig.XrayServerUser,
		Password: operatorConfig.XrayServerPassword,
	}

	client, err := xray.NewClientWithToken(operatorConfig.XrayServerUrl, &credentials)
	if err != nil {
		logger.Error().Msgf("Error when generating Xray Token: %v", err)
	}

	result := &XrayService{
		logger:       logger,
		xrayClient:   client,
		xrayBinMgrID: operatorConfig.XrayBinMgrID,
		Credentials:   &credentials,
	}

	return result, err
}

func (s *XrayService) RenewXrayToken() {
	client, err := xray.NewClientWithToken(os.Getenv("ARTI_OP_XRAY_SERVER_URL"), s.Credentials)
	if err != nil {
		s.logger.Error().Msgf("Error when generating Xray Token: %v", err)
	}
	s.logger.Info().Msgf("Xray Token has been renewed")
	s.xrayClient = client
}

func (s *XrayService) CreatePolicy(client *xray.Client, policy *xray.Policy) (*http.Response, error) {
	resp, err := client.Policies.CreatePolicies(context.Background(), policy)
	fmt.Println("TOTOTOTOTO")
	fmt.Println(err)
	fmt.Println("TOTOTOTOTO")

	if resp.StatusCode == http.StatusUnauthorized {
		s.RenewXrayToken()
		resp, err := client.Policies.CreatePolicies(context.Background(), policy)
		if err != nil {
			return nil, err
		}
		return resp, err
	} else 	if err != nil {
		return nil, err
	}
	return resp, err
}

func (s *XrayService) UpdatePolicy(client *xray.Client, policy *xray.Policy, name string) (*http.Response, error) {

	resp, err := client.Policies.UpdatePolicies(context.Background(), policy, name)
	if resp.StatusCode == http.StatusUnauthorized {
		s.RenewXrayToken()
		resp, err := client.Policies.UpdatePolicies(context.Background(), policy, name)
		if err != nil {
			return nil, err
		}
		return resp, err
	} else 	if err != nil {
		return nil, err
	}
	return resp, err
}

func (s *XrayService) CreateWatch(client *xray.Client, watch *xray.Watch) (*http.Response, error) {

	resp, err := client.Watches.CreateWatch(context.Background(), watch)
	if resp.StatusCode == http.StatusUnauthorized {
		s.RenewXrayToken()
		resp, err := client.Watches.CreateWatch(context.Background(), watch)
		if err != nil {
			return nil, err
		}
		return resp, err
	} else 	if err != nil {
		return nil, err
	}
	return resp, err
}

func (s *XrayService) UpdateWatch(client *xray.Client, watch *xray.Watch, name string) (*http.Response, error) {

	resp, err := client.Watches.UpdateWatch(context.Background(), watch, name)
	if resp.StatusCode == http.StatusUnauthorized {
		s.RenewXrayToken()
		resp, err := client.Watches.UpdateWatch(context.Background(), watch, name)
		if err != nil {
			return nil, err
		}
		return resp, err
	} else 	if err != nil {
		return nil, err
	}
	return resp, err
}

// Should return true if repoName is "stable"
func (s *XrayService) checkKindofRepo(repoName string) bool {
	r, err := regexp.Compile(utils.XrayRegexRepoStable)
	if err != nil {
		s.logger.Error().Msgf("Regexp encountered a problem: %v", err)
	} else if r.MatchString(repoName) {
		return true
	} else {
		return false
	}
	return false
}

func (s *XrayService) policyFields(repoName string) *xray.Policy {
	return &xray.Policy{
		Name: repoName,
		Type: utils.AssignedPolicyType,
		Rules: []xray.Rule{{
			Name:     repoName,
			Priority: utils.XrayPolicyRulePriority,
			Criteria: xray.Criteria{
				MinSeverity: utils.PolicyMinSeverity,
			},
			Actions: xray.Action{
				Mails:     []string{utils.XrayPolicyActionMail},
				FailBuild: false,
				BlockDownload: xray.BlockDownload{
					Unscanned: s.checkKindofRepo(repoName),
					Active:    s.checkKindofRepo(repoName),
				},
			}},
		},
		Description: "Policy generated by Artifactory Operator",
	}
}

func (s *XrayService) createXrayPolicy(repos []string) {
	for _, repoName := range repos {
		policy := s.policyFields(repoName)
		resp, err := s.CreatePolicy(s.xrayClient, policy)

		if resp != nil {
			if resp.StatusCode == http.StatusCreated {
				s.logger.Info().Msgf("XRAY Policy repo %v was created correctly", repoName)
				continue
			}
		} else if err != nil {
			if err.Error() == `{"error":"Policy already exists"}` {
				s.logger.Info().Msgf("XRAY Policy for repo %v already exists, try to update it", repoName)
				_, err := s.UpdatePolicy(s.xrayClient, policy, repoName)
				if err != nil {
					s.logger.Error().Msgf("Could not update XRAY Policy for repo %v: %v", repoName, err)
				} else {
					s.logger.Info().Msgf("XRAY Policy repo %v was updated correctly", repoName)
				}
			} else {
				s.logger.Error().Msgf("Could not create nor update XRAY Policy for repo %v: %v", repoName, err)
			}
		}

	}
}

func (s *XrayService) watchFields(repoName string) *xray.Watch {

	filters := &xray.Filters{
		Type:  utils.XrayWatchFilterType,
		Value: utils.XrayWatchFilterValue,
	}

	resources := &xray.Resources{
		Type:     utils.ResourceType,
		BinMgrID: s.xrayBinMgrID,
		RepoType: utils.RepoType,
		Name:     repoName,
		Filters:  []xray.Filters{*filters},
	}

	assignedPolicy := &xray.AssignedPolicies{
		Name: repoName,
		Type: utils.AssignedPolicyType,
	}

	result := &xray.Watch{
		GeneralData: xray.GeneralData{
			Name:        repoName,
			Description: utils.XrayWatchDescription,
			Active:      true,
		},
		ProjectResources: xray.ProjectResources{
			Resources: []xray.Resources{*resources},
		},
		AssignedPolicies: []xray.AssignedPolicies{*assignedPolicy},
	}

	return result
}

func (s *XrayService) createXrayWatch(repos []string) {
	for _, repoName := range repos {
		watch := s.watchFields(repoName)
		resp, err := s.CreateWatch(s.xrayClient, watch)

		if resp != nil {
			if resp.StatusCode == http.StatusCreated {
				s.logger.Info().Msgf("XRAY Watch repo %v was created correctly", repoName)
				continue
			}
		} else if err != nil {
			if err.Error() == `{"error":"Watch already exists"}` {
				s.logger.Info().Msgf("XRAY Watch for repo %v already exists, try to update it", repoName)
				_, err := s.UpdateWatch(s.xrayClient, watch, repoName)
				if err != nil {
					s.logger.Error().Msgf("Could not update XRAY Watch for repo %v: %v", repoName, err)
				} else {
					s.logger.Info().Msgf("XRAY Watch repo %v was updated correctly", repoName)
				}
			} else {
				s.logger.Error().Msgf("Could not create nor update XRAY Watch for repo %v: %v", repoName, err)
			}
		}

	}
}
