package utils

const (
	DockerRemote      = "docker-remote.registry.saas.cagip.gca"
	DockerRemoteGroup = "docker-remote.registry.saas.cagip.group.gca"
	Domain            = ".registry.saas.cagip.gca"
	DomainGroup       = ".registry.saas.cagip.group.gca"
	WhitelistKey      = "whitelist-repositories"
	VaultStore        = "secret/data"
)

// Const for Artifactory tests
const (
	ArtifactoryTestTenant                     = "aug"
	ArtifactoryTestProjectName                = "e4"
	ArtifactoryTestPermissionRO               = "aug-e4-docker-allrepos-intranet-ro"
	ArtifactoryTestPermissionRW               = "aug-e4-docker-allrepos-intranet-rw"
	ArtifactoryTestProjectMetaNameDevelopment = "aug-e4-development"
)

const (
	DefaultPasswordStoreBackendNamespace = "kube-system"
	DefaultPasswordStoreSecretNamePrefix = "artifactory-user"
	ResourceType                         = "repository"
)

const (
	ArtifactoryProjectSpecEnvironment    = "development"
	ArtifactoryLocationIntranet          = "intranet"
	ArtifactoryLocationExtranet          = "extranet"
	ArtifactoryDescription               = "Generated by artifactory operator"
	ArtifactoryUserROSuffixNonProduction = "k8s_reader"
	ArtifactoryUserRWSuffix              = "jenkins_writer"
)

var AllowedClusterLocations = []string{ArtifactoryLocationExtranet, ArtifactoryLocationIntranet}

const (
	ArtifactoryStageScratch = "scratch"
	ArtifactoryStageStaging = "staging"
	ArtifactoryStageStable  = "stable"
)
