package utils

const (
	DockerRemote      = "docker-remote.registry.saas.cagip.gca"
	DockerRemoteGroup = "docker-remote.registry.saas.cagip.gca"
	Domain            = ".registry.saas.cagip.gca"
	DomainGroup       = ".registry.saas.cagip.group.gca"
	WhitelistKey      = "whitelist-repositories"
	VaultStore        = "secret/data"
)

// Const for Xray tests
const (
	XrayTestRepoScratch = "aug-e4-docker-scratch-intranet"
	XrayTestRepoStaging = "aug-e4-docker-staging-intranet"
	XrayTestRepoStable  = "aug-e4-docker-stable-intranet"
	XrayTestBinMgrID    = "arti-rct"
)

// Const for Artifactory tests
const (
	ArtifactoryTestTenant                     = "aug"
	ArtifactoryTestProjectName                = "e4"
	ArtifactoryTestPermissionRO               = "aug-e4-docker-allrepos-intranet-ro"
	ArtifactoryTestPermissionRW               = "aug-e4-docker-allrepos-intranet-rw"
	ArtifactoryTestProjectMetaNameDevelopment = "aug-e4-development"
)

const (
	DefaultPasswordStoreBackendNamespace = "kube-system"
	DefaultPasswordStoreSecretNamePrefix = "artifactory-user"
	ResourceType                         = "repository"
	RepoType                             = "local"
	AssignedPolicyType                   = "security"
	PolicyMinSeverity                    = "High"
	XrayWatchDescription                 = "This is a new watch created with the artifactory operator"
	XrayWatchFilterType                  = "regex"
	XrayWatchFilterValue                 = ".*"
	XrayPolicyActionMail                 = "operator@example.com"
	XrayPolicyRulePriority               = 1
	XrayRegexRepoStable                  = ".*stable"
)

const (
	ArtifactoryProjectSpecEnvironment           = "development"
	ArtifactoryProjectSpecEnvironmentProduction = "production"
	ArtifactoryLocationIntranet                 = "intranet"
	ArtifactoryLocationExtranet                 = "extranet"
	ArtifactoryDescription                      = "Generated by artifactory operator"
	ArtifactoryUserROSuffixNonProduction        = "k8s_reader"
	ArtifactoryUserROSuffixProduction           = "k8s_production_reader"
	ArtifactoryUserRWSuffix                     = "jenkins_writer"
)

var AllowedClusterLocations = []string{ArtifactoryLocationExtranet, ArtifactoryLocationIntranet}

const (
	ArtifactoryStageScratch = "scratch"
	ArtifactoryStageStaging = "staging"
	ArtifactoryStageStable  = "stable"
)

var AllowedStages = []string{ArtifactoryStageScratch, ArtifactoryStageStaging, ArtifactoryStageStable}

const (
	ArtifactoryUserRead  = "k8s_reader"
	ArtifactoryUserWrite = "jenkins_writer"
)
